### ISSUE TITLE
Should `/mnt/borg_config` be writeable?

### ISSUE THREAD

**Issue by bbbenji** [knthmn/docker-borgmatic-rclone#4]
The example docker-compose.yaml in the README sets `/mnt/borg_config` as Read Only. I was unable to get this container working correctly until I mounted that directory as writeable.

Also, could you please share your Borgmatic and RClone configs?

**Comment by knthmn** [comment]
Thanks for the issue. I have made a mistake in the docs. `/mnt/borg_config` should indeed be writable for borg to keep track of the repo's status [1].

rclone config is just configured normally with `rclone config`, you just need to match the `DESTINATION` env to the remote (or a path under a remote) you want to back up to. I have also attached the borgmatic config I am currently using below.

1: https://borgbackup.readthedocs.io/en/stable/faq.html#home-config-borg

### borgmatic config
```
location:
    # List of source directories to backup. Globs are expanded.
    source_directories:
        - /mnt/source/client_home
        - /mnt/source/library

    # Paths to local or remote repositories.
    repositories:
        - /mnt/repo 

storage:
    archive_name_format: files-{now:%Y%m%dT%H%M%S}
    unknown_unencrypted_repo_access_is_ok: true

retention:
    # Retention policy for how many backups to keep in each category.
    keep_hourly: 24
    keep_daily: 14 # = 2 weeks
    keep_weekly: 8 # = 2 months
    keep_monthly: 12
    prefix: files

consistency:
    checks:
        - disabled
```
